all: precomputation.cpp precomputation_BT.cpp
	g++ -o precomputation.o precomputation.cpp --std=c++11
	g++ -o precomputation_BT.o precomputation_BT.cpp --std=c++11
clean:
	rm precomputation.o precomputation_BT.o
