all: analyzeLoopOnline.cpp analyzeLoopWithSwid.cpp
	g++ -o analyzeLoopOnline analyzeLoopOnline.cpp --std=c++11 -g
	g++ -o analyzeLoopWithSwid analyzeLoopWithSwid.cpp --std=c++11 -g
clean:
	rm analyzeLoopOnline analyzeLoopWithSwid
